### PR TITLE
File import errors in Emissions workspace

### LINKED ISSUE #5972: File import errors in Emissions workspace
**From original [ntknguyen](https://github.com/ntknguyen) ([Theresa Nguyen](https://github.com/ntknguyen)) comment.**

Missing sorbent-trap.entity in the [code-check-utils.ts](https://github.com/US-EPA-CAMD/easey-emissions-api/blob/develop/src/code-checks/code-checks-utils.ts) and the ["apsCode" code map](https://github.com/US-EPA-CAMD/easey-emissions-api/blob/develop/src/code-checks/code-checks.service.ts#L191) is incorrect.

**Steps to reproduce the issues**:

1. Select Mill Creek config 1,2,CS12
2. Import 2023 Q1 emissions from historical data

### Additional Notes:

**Code Checking Key Methods/Variables**:
1. src / **code-checks.service.ts** -> CodeChecksService.**runChecks**( payload: EmissionsImportDTO )
2. src / **code-checks-utils.ts** -> **getCodeFieldRepoList**()
3. src / **code-checks.service.ts** -> CodeChecksService.**collectSorbentTrapData**( payload: SorbentTrapImportDTO[], codesMap: Map<string, Set<string>> )
4. src / **code-checks-utils.ts** -> **getInvalidCodes**( codeSet: Set<string>, entityRepo: Repository<BaseEntity> )

**Code Checking Notes**:
1. **runChecks** is called to check emissions data.
2. **runChecks** calls **getCodeFieldRepoList** to get the list of "defined" codes (JSON fields) with their allowed code values.
3. **runChecks** calls **collectSorbentTrapData** to collect the list of field name/values pairs for each sorbent trap and child sampling train JSON code fields, including APS Code.
4. For each defined code returned by **getCodeFieldRepoList**, **runChecks** passes the codes for the matching code field in the Sorbent Trap or Sampling Train data and the allowed code values to **getInvalidCodes**, which returns a unique list of the codes not in the expected lookup table.

**The Problem**
1. The "**apsCode**" JSON field name is shared by both the QA and emissions JSON files, by RATA in the QA JSON and by Sorbent Traps in the emissions JSON.
2. Currently, the **getCodeFieldRepoList** method returns a list of JSON code field and their corresponding database lookup values.   **getCodeFieldRepoList** determines the field names it handles and which database table contains the lookup values.
3. For the "**apsCode**" JSON field, **getCodeFieldRepoList** currently uses the camdecmpsmd.**APS_CODE** table as the lookup table instead of the camdecmpsmd.**SORBENT_TRAP_APS_CODE** table.
4. The camdecmpsmd.**APS_CODE** table contains the RATA APS Codes.
5. The camdecmpsmd.**SORBENT_TRAP_APS_CODE** table contains the Sorbent Trap APS Codes.

**Proposed Solution**
1. Generate an entity class file **SorbentTrapApsCode** for camdecmpsmd.**SORBENT_TRAP_APS_CODE**, with the **SORBENT_TRAP_APS_CD** column as the primary column.
2. Note that the **ApsCode** entity class (src / aps-code.entity.ts) should not be needed for emissions.
4. Update the "**apsCode**" element handling in **getCodeFieldRepoList**(), changing the reference for the **ApsCode** entity class to the new **SorbentTrapApsCode** entity class.  The **codeField** should remain as "**apsCode**".
5. Updated the src / **sorbent-trap.entity.ts** definition for **SORBENT_TRAP_APS_CD** to include a one-to-many join to **SorbentTrapApsCode**.
6. Update Runbook or other documentation with the code checking method.

### PR DESCRIPTION
**Pull request by shahbazkhan1999**

### CODE REVIEW

**Review by ergjustin — CHANGES_REQUESTED** [review]
Some checks failed. You need update SonarCloud token. Send a message to Michael for updating SonarCloud token.

**Review by ergjustin — COMMENTED** [review]
Are you sure this changes will merge with **develop** branch ?

**Comment by shahbazkhan1999** [comment]
> Are you sure this changes will merge with **develop** branch ?

yes

**Review by ergjustin — APPROVED** [review]

**Comment by maheese** [comment]
This pull request is supposed to fix us-epa-camd/easey-ui#5972 but it does not address the issue described in the ticket.

**Pull request merged**
